name: taskmaster
description: Intelligent Task Manager

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  flutter_local_notifications: ^19.4.1
  intl: ^0.20.2
  table_calendar: ^3.0.8
  uuid: ^4.3.3

# assets
flutter:
  uses-material-design: true
  assets:
    - lib/assets/app_background.png
    - lib/assets/app_logo.png
